title: "Войтов Андрей Михайлович"
description: "Руководитель проекта / продукта"

url: "https://amvoitov.github.io"
baseurl: "/amvoitoiv.github.io"

defaults:
  - scope:
      path: ""
    values:
      layout: default
